project_name: aws-services
version: 2

before:
  hooks:
    - go mod tidy
    - ./assets/scripts/completions.sh

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: aws-services
    ldflags:
      - -s -w -X main.build={{.Version}}

brews:
  -
    repository:
      owner: rollwagen
      name: homebrew-tap
    license: Apache-2.0
    install: |-
      bin.install "aws-services"
      bash_completion.install "completions/aws-services.bash" => "aws-services"
      zsh_completion.install "completions/aws-services.zsh" => "_aws-services"
      fish_completion.install "completions/aws-services.fish"

checksum:
  name_template: checksums.txt

signs:
  - cmd: cosign
    stdin: "{{ .Env.COSIGN_PWD }}"
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - --key=assets/cosign/cosign.key
      - --bundle=${signature}
      - --yes
      - ${artifact}
    artifacts: checksum

archives:
  - files:
      - README.md
      - LICENSE
      - completions/*

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
